name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs: 
      ci:
        runs-on: ubuntu-latest
        steps: 
          - name: Autententicar no Docker Hub
            run: echo "Executando o comando Docker Login"
          - name: Construção da Imagem da Docker
            run: echo "Executando o comando Docker build"
          - name: Envio da Imagem Docker
            run: echo "Executando o comando Docker push"

      cd:
        runs-on: ubuntu-latest
        steps: 
          - name: Autententicar na AWS
            run: echo "Executando o comando aws configure"
          - name: Configurar o kubectl
            run: "Configurar o kubectl aws eks update-kubeconfig"
          - name: "Deploy dos manifestos do Kubernetes"
            run: echo "Executando o comando kubectl apply"
